### ISSUE TITLE
An error occurred while installing ruby_dep (1.4.0), and Bundler cannot

### ISSUE THREAD

**Issue by pavankuppa** [e2/ruby_dep#23]
An error occurred while installing ruby_dep (1.4.0), and Bundler cannot
Make sure that `gem install ruby_dep -v '1.4.0'` succeeds before bundling

**Comment by e2** [comment]
If you're using Listen, downgrade to Listen v3.0.8, which should let you install.

A newer version of Bundler may do this for you automatically.

For Ruby 1.9.3 support, you can install the latest Listen 2.x.x, which doesn't have such restrictions.
