### ISSUE TITLE
bundle install fails for gem when it worked before

### ISSUE THREAD

**Issue by monkbroc** [e2/ruby_dep#29]
I want to start by thanking you for all your open source contributions in the Ruby world. I'm a big fan of the nenv gem.

I am maintaining a gem called [particlerb](https://github.com/monkbroc/particlerb). It used to install fine with older rubies but now I get an error when doing `bundle install` on Ruby 2.1.8.

```
Gem::InstallError: ruby_dep requires Ruby version >= 2.2.5, ~> 2.2.
```

I'm confused as to what ruby_dep is, and why it's causing the installation to fail when it used to work properly.

I tracked down the failure to `guard-rspec` in the gemspec. `bundle install` works when I remove that gem and fails when I add it back. I tried locking the version of `guard-rspec` to 4.5.2 which is the version from 2015 that I initially used to develop this gem, but I still get the error.

Can you help me figure out what's going on and how to keep supporting the same rubies I supported last year?

**Comment by e2** [comment]
Thanks - glad to hear!

To support older Rubies, just lock your version of Listen to '~> 3.0.8'.

That version doesn't require ruby_dep, so everything else should work
fine. (As long as you don't have ruby_dep added manually somewhere).

**Comment by monkbroc** [comment]
Great. Thanks for the advice. I'm going to try that.

It seems you're trying to solve the issue of making the Ruby version part of the bundle dependency process, but the pains of loose versions of 2nd or 3rd level dependencies are making it difficult to deploy this gradually. Thanks for spending your time and energy pushing this noble goal forward.

**Comment by monkbroc** [comment]
That solves the issue for me. Thanks!
