### ISSUE TITLE
ruby_dep requires Ruby version >= 2.2.5, ~> 2.2

### ISSUE THREAD

**Issue by yb66** [e2/ruby_dep#31]
Hello,

```
Gem::InstallError: ruby_dep requires Ruby version >= 2.2.5, ~> 2.2.
An error occurred while installing ruby_dep (1.5.0), and Bundler cannot continue.
Make sure that `gem install ruby_dep -v '1.5.0'` succeeds before bundling.
```

```
ruby --version
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin13]
```

2.4 is >= 2.2.5 and for the ~> the .4 is greater than .2. What am I missing here?

Regards,
iain

**Comment by yb66** [comment]
Something went wrong with my path. Who knows why.

**Comment by im-gerardo** [comment]
Hi, if you are using RMV (Ruby Version Manager) just run 
`rvm install 2.2.5`

i dont know why that unistalled rails, but im just installed again with 
`sudo gem install rails `

after that i installed 
`gem install bundler --pre `

and finally 
`bundle install`

So that works for me!
